[package]
name = "web"
version = "0.1.0"
authors = ["archification <archification@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.4"
multipart = "0.16.1"
rocket_upload = "0.1.0"

[dependencies.rocket_contrib]
version = "0.4.4"
features = ["tera_templates"]
